### ISSUE TITLE
Why not use Smithay?

### ISSUE THREAD

**Issue by firasuke** [schickst/waybox#1]
Why not use [Smithay](https://github.com/Smithay/smithay) to ensure that everything is written in Rust?

**Comment by schickst** [comment]
I was actually unsure what to use. Smithay has the adavantage that it is written in rust. wlroots on the other hand needs unsafe wrapping, but is overall a more mature project. So I thought I'd start with wlroots and try to create clean abstractions to keep the future as open as possible.
In an ideal world with the right abstractions I later would be able to interchange the two. If this works I don't know, yet.

Another idea would be to improve Smithay forward at the same time. For this task I do not feel qualified yet.

**Comment by firasuke** [comment]
I see.

Still consider giving Smithay a try after you've got the hang of wlroots.

**Comment by schickst** [comment]
Gets tracked in #5

**Comment by firasuke** [comment]
Good luck with your endeavors!
